// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Games.TLBB.Table.Static
{

using global::System;
using global::FlatBuffers;
using System.Collections.Generic;

public struct SkillDataTableVO : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SkillDataTableVO GetRootAsSkillDataTableVO(ByteBuffer _bb) { return GetRootAsSkillDataTableVO(_bb, new SkillDataTableVO()); }
  public static SkillDataTableVO GetRootAsSkillDataTableVO(ByteBuffer _bb, SkillDataTableVO obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SkillDataTableVO __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CehuaId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
  public string DescforTips { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetDescforTipsBytes() { return __p.__vector_as_arraysegment(10); }
  public string DescForInterFace { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetDescForInterFaceBytes() { return __p.__vector_as_arraysegment(12); }
  public int LogicId { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Cdtime { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ChargeTime { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int GuideTime { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ConDepDesc0 { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetConDepDesc0Bytes() { return __p.__vector_as_arraysegment(22); }
  public int Type0 { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Type0Param0 { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Type0Param1 { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Type0Note { get { int o = __p.__offset(30); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetType0NoteBytes() { return __p.__vector_as_arraysegment(30); }
  public int Type1 { get { int o = __p.__offset(32); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Type1Param0 { get { int o = __p.__offset(34); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Type1Param1 { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Type1Note { get { int o = __p.__offset(38); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetType1NoteBytes() { return __p.__vector_as_arraysegment(38); }
  public int Type2 { get { int o = __p.__offset(40); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Type2Param0 { get { int o = __p.__offset(42); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Type2Param1 { get { int o = __p.__offset(44); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Type2Note { get { int o = __p.__offset(46); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxChargePoint { get { int o = __p.__offset(48); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Reserved2 { get { int o = __p.__offset(50); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc0 { get { int o = __p.__offset(52); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc0Bytes() { return __p.__vector_as_arraysegment(52); }
  public int ImpactParam0 { get { int o = __p.__offset(54); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc1 { get { int o = __p.__offset(56); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc1Bytes() { return __p.__vector_as_arraysegment(56); }
  public int ImpactParam1 { get { int o = __p.__offset(58); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc2 { get { int o = __p.__offset(60); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc2Bytes() { return __p.__vector_as_arraysegment(60); }
  public int ImpactParam2 { get { int o = __p.__offset(62); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc3 { get { int o = __p.__offset(64); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc3Bytes() { return __p.__vector_as_arraysegment(64); }
  public int ImpactParam3 { get { int o = __p.__offset(66); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc4 { get { int o = __p.__offset(68); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc4Bytes() { return __p.__vector_as_arraysegment(68); }
  public int ImpactParam4 { get { int o = __p.__offset(70); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc5 { get { int o = __p.__offset(72); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc5Bytes() { return __p.__vector_as_arraysegment(72); }
  public int ImpactParam5 { get { int o = __p.__offset(74); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc6 { get { int o = __p.__offset(76); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc6Bytes() { return __p.__vector_as_arraysegment(76); }
  public int ImpactParam6 { get { int o = __p.__offset(78); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc7 { get { int o = __p.__offset(80); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc7Bytes() { return __p.__vector_as_arraysegment(80); }
  public int ImpactParam7 { get { int o = __p.__offset(82); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc8 { get { int o = __p.__offset(84); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc8Bytes() { return __p.__vector_as_arraysegment(84); }
  public int ImpactParam8 { get { int o = __p.__offset(86); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc9 { get { int o = __p.__offset(88); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc9Bytes() { return __p.__vector_as_arraysegment(88); }
  public int ImpactParam9 { get { int o = __p.__offset(90); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc10 { get { int o = __p.__offset(92); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc10Bytes() { return __p.__vector_as_arraysegment(92); }
  public int ImpactParam10 { get { int o = __p.__offset(94); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ImpactDesc11 { get { int o = __p.__offset(96); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetImpactDesc11Bytes() { return __p.__vector_as_arraysegment(96); }
  public int ImpactParam12 { get { int o = __p.__offset(98); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Show1 { get { int o = __p.__offset(100); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetShow1Bytes() { return __p.__vector_as_arraysegment(100); }
  public string Show2 { get { int o = __p.__offset(102); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetShow2Bytes() { return __p.__vector_as_arraysegment(102); }

  public static Offset<SkillDataTableVO> CreateSkillDataTableVO(FlatBufferBuilder builder,
      int Id = 0,
      int cehuaId = 0,
      StringOffset nameOffset = default(StringOffset),
      StringOffset descforTipsOffset = default(StringOffset),
      StringOffset descForInterFaceOffset = default(StringOffset),
      int logicId = 0,
      int cdtime = 0,
      int chargeTime = 0,
      int guideTime = 0,
      StringOffset conDepDesc0Offset = default(StringOffset),
      int type0 = 0,
      int type0Param0 = 0,
      int type0Param1 = 0,
      StringOffset type0NoteOffset = default(StringOffset),
      int type1 = 0,
      int type1Param0 = 0,
      int type1Param1 = 0,
      StringOffset type1NoteOffset = default(StringOffset),
      int type2 = 0,
      int type2Param0 = 0,
      int type2Param1 = 0,
      int type2Note = 0,
      int MaxChargePoint = 0,
      int Reserved2 = 0,
      StringOffset impactDesc0Offset = default(StringOffset),
      int impactParam0 = 0,
      StringOffset impactDesc1Offset = default(StringOffset),
      int impactParam1 = 0,
      StringOffset impactDesc2Offset = default(StringOffset),
      int impactParam2 = 0,
      StringOffset impactDesc3Offset = default(StringOffset),
      int impactParam3 = 0,
      StringOffset impactDesc4Offset = default(StringOffset),
      int impactParam4 = 0,
      StringOffset impactDesc5Offset = default(StringOffset),
      int impactParam5 = 0,
      StringOffset impactDesc6Offset = default(StringOffset),
      int impactParam6 = 0,
      StringOffset impactDesc7Offset = default(StringOffset),
      int impactParam7 = 0,
      StringOffset impactDesc8Offset = default(StringOffset),
      int impactParam8 = 0,
      StringOffset impactDesc9Offset = default(StringOffset),
      int impactParam9 = 0,
      StringOffset impactDesc10Offset = default(StringOffset),
      int impactParam10 = 0,
      StringOffset impactDesc11Offset = default(StringOffset),
      int impactParam12 = 0,
      StringOffset Show1Offset = default(StringOffset),
      StringOffset Show2Offset = default(StringOffset)) {
    builder.StartObject(50);
    SkillDataTableVO.AddShow2(builder, Show2Offset);
    SkillDataTableVO.AddShow1(builder, Show1Offset);
    SkillDataTableVO.AddImpactParam12(builder, impactParam12);
    SkillDataTableVO.AddImpactDesc11(builder, impactDesc11Offset);
    SkillDataTableVO.AddImpactParam10(builder, impactParam10);
    SkillDataTableVO.AddImpactDesc10(builder, impactDesc10Offset);
    SkillDataTableVO.AddImpactParam9(builder, impactParam9);
    SkillDataTableVO.AddImpactDesc9(builder, impactDesc9Offset);
    SkillDataTableVO.AddImpactParam8(builder, impactParam8);
    SkillDataTableVO.AddImpactDesc8(builder, impactDesc8Offset);
    SkillDataTableVO.AddImpactParam7(builder, impactParam7);
    SkillDataTableVO.AddImpactDesc7(builder, impactDesc7Offset);
    SkillDataTableVO.AddImpactParam6(builder, impactParam6);
    SkillDataTableVO.AddImpactDesc6(builder, impactDesc6Offset);
    SkillDataTableVO.AddImpactParam5(builder, impactParam5);
    SkillDataTableVO.AddImpactDesc5(builder, impactDesc5Offset);
    SkillDataTableVO.AddImpactParam4(builder, impactParam4);
    SkillDataTableVO.AddImpactDesc4(builder, impactDesc4Offset);
    SkillDataTableVO.AddImpactParam3(builder, impactParam3);
    SkillDataTableVO.AddImpactDesc3(builder, impactDesc3Offset);
    SkillDataTableVO.AddImpactParam2(builder, impactParam2);
    SkillDataTableVO.AddImpactDesc2(builder, impactDesc2Offset);
    SkillDataTableVO.AddImpactParam1(builder, impactParam1);
    SkillDataTableVO.AddImpactDesc1(builder, impactDesc1Offset);
    SkillDataTableVO.AddImpactParam0(builder, impactParam0);
    SkillDataTableVO.AddImpactDesc0(builder, impactDesc0Offset);
    SkillDataTableVO.AddReserved2(builder, Reserved2);
    SkillDataTableVO.AddMaxChargePoint(builder, MaxChargePoint);
    SkillDataTableVO.AddType2Note(builder, type2Note);
    SkillDataTableVO.AddType2Param1(builder, type2Param1);
    SkillDataTableVO.AddType2Param0(builder, type2Param0);
    SkillDataTableVO.AddType2(builder, type2);
    SkillDataTableVO.AddType1Note(builder, type1NoteOffset);
    SkillDataTableVO.AddType1Param1(builder, type1Param1);
    SkillDataTableVO.AddType1Param0(builder, type1Param0);
    SkillDataTableVO.AddType1(builder, type1);
    SkillDataTableVO.AddType0Note(builder, type0NoteOffset);
    SkillDataTableVO.AddType0Param1(builder, type0Param1);
    SkillDataTableVO.AddType0Param0(builder, type0Param0);
    SkillDataTableVO.AddType0(builder, type0);
    SkillDataTableVO.AddConDepDesc0(builder, conDepDesc0Offset);
    SkillDataTableVO.AddGuideTime(builder, guideTime);
    SkillDataTableVO.AddChargeTime(builder, chargeTime);
    SkillDataTableVO.AddCdtime(builder, cdtime);
    SkillDataTableVO.AddLogicId(builder, logicId);
    SkillDataTableVO.AddDescForInterFace(builder, descForInterFaceOffset);
    SkillDataTableVO.AddDescforTips(builder, descforTipsOffset);
    SkillDataTableVO.AddName(builder, nameOffset);
    SkillDataTableVO.AddCehuaId(builder, cehuaId);
    SkillDataTableVO.AddId(builder, Id);
    return SkillDataTableVO.EndSkillDataTableVO(builder);
  }

  public static void StartSkillDataTableVO(FlatBufferBuilder builder) { builder.StartObject(50); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddCehuaId(FlatBufferBuilder builder, int cehuaId) { builder.AddInt(1, cehuaId, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
  public static void AddDescforTips(FlatBufferBuilder builder, StringOffset descforTipsOffset) { builder.AddOffset(3, descforTipsOffset.Value, 0); }
  public static void AddDescForInterFace(FlatBufferBuilder builder, StringOffset descForInterFaceOffset) { builder.AddOffset(4, descForInterFaceOffset.Value, 0); }
  public static void AddLogicId(FlatBufferBuilder builder, int logicId) { builder.AddInt(5, logicId, 0); }
  public static void AddCdtime(FlatBufferBuilder builder, int cdtime) { builder.AddInt(6, cdtime, 0); }
  public static void AddChargeTime(FlatBufferBuilder builder, int chargeTime) { builder.AddInt(7, chargeTime, 0); }
  public static void AddGuideTime(FlatBufferBuilder builder, int guideTime) { builder.AddInt(8, guideTime, 0); }
  public static void AddConDepDesc0(FlatBufferBuilder builder, StringOffset conDepDesc0Offset) { builder.AddOffset(9, conDepDesc0Offset.Value, 0); }
  public static void AddType0(FlatBufferBuilder builder, int type0) { builder.AddInt(10, type0, 0); }
  public static void AddType0Param0(FlatBufferBuilder builder, int type0Param0) { builder.AddInt(11, type0Param0, 0); }
  public static void AddType0Param1(FlatBufferBuilder builder, int type0Param1) { builder.AddInt(12, type0Param1, 0); }
  public static void AddType0Note(FlatBufferBuilder builder, StringOffset type0NoteOffset) { builder.AddOffset(13, type0NoteOffset.Value, 0); }
  public static void AddType1(FlatBufferBuilder builder, int type1) { builder.AddInt(14, type1, 0); }
  public static void AddType1Param0(FlatBufferBuilder builder, int type1Param0) { builder.AddInt(15, type1Param0, 0); }
  public static void AddType1Param1(FlatBufferBuilder builder, int type1Param1) { builder.AddInt(16, type1Param1, 0); }
  public static void AddType1Note(FlatBufferBuilder builder, StringOffset type1NoteOffset) { builder.AddOffset(17, type1NoteOffset.Value, 0); }
  public static void AddType2(FlatBufferBuilder builder, int type2) { builder.AddInt(18, type2, 0); }
  public static void AddType2Param0(FlatBufferBuilder builder, int type2Param0) { builder.AddInt(19, type2Param0, 0); }
  public static void AddType2Param1(FlatBufferBuilder builder, int type2Param1) { builder.AddInt(20, type2Param1, 0); }
  public static void AddType2Note(FlatBufferBuilder builder, int type2Note) { builder.AddInt(21, type2Note, 0); }
  public static void AddMaxChargePoint(FlatBufferBuilder builder, int MaxChargePoint) { builder.AddInt(22, MaxChargePoint, 0); }
  public static void AddReserved2(FlatBufferBuilder builder, int Reserved2) { builder.AddInt(23, Reserved2, 0); }
  public static void AddImpactDesc0(FlatBufferBuilder builder, StringOffset impactDesc0Offset) { builder.AddOffset(24, impactDesc0Offset.Value, 0); }
  public static void AddImpactParam0(FlatBufferBuilder builder, int impactParam0) { builder.AddInt(25, impactParam0, 0); }
  public static void AddImpactDesc1(FlatBufferBuilder builder, StringOffset impactDesc1Offset) { builder.AddOffset(26, impactDesc1Offset.Value, 0); }
  public static void AddImpactParam1(FlatBufferBuilder builder, int impactParam1) { builder.AddInt(27, impactParam1, 0); }
  public static void AddImpactDesc2(FlatBufferBuilder builder, StringOffset impactDesc2Offset) { builder.AddOffset(28, impactDesc2Offset.Value, 0); }
  public static void AddImpactParam2(FlatBufferBuilder builder, int impactParam2) { builder.AddInt(29, impactParam2, 0); }
  public static void AddImpactDesc3(FlatBufferBuilder builder, StringOffset impactDesc3Offset) { builder.AddOffset(30, impactDesc3Offset.Value, 0); }
  public static void AddImpactParam3(FlatBufferBuilder builder, int impactParam3) { builder.AddInt(31, impactParam3, 0); }
  public static void AddImpactDesc4(FlatBufferBuilder builder, StringOffset impactDesc4Offset) { builder.AddOffset(32, impactDesc4Offset.Value, 0); }
  public static void AddImpactParam4(FlatBufferBuilder builder, int impactParam4) { builder.AddInt(33, impactParam4, 0); }
  public static void AddImpactDesc5(FlatBufferBuilder builder, StringOffset impactDesc5Offset) { builder.AddOffset(34, impactDesc5Offset.Value, 0); }
  public static void AddImpactParam5(FlatBufferBuilder builder, int impactParam5) { builder.AddInt(35, impactParam5, 0); }
  public static void AddImpactDesc6(FlatBufferBuilder builder, StringOffset impactDesc6Offset) { builder.AddOffset(36, impactDesc6Offset.Value, 0); }
  public static void AddImpactParam6(FlatBufferBuilder builder, int impactParam6) { builder.AddInt(37, impactParam6, 0); }
  public static void AddImpactDesc7(FlatBufferBuilder builder, StringOffset impactDesc7Offset) { builder.AddOffset(38, impactDesc7Offset.Value, 0); }
  public static void AddImpactParam7(FlatBufferBuilder builder, int impactParam7) { builder.AddInt(39, impactParam7, 0); }
  public static void AddImpactDesc8(FlatBufferBuilder builder, StringOffset impactDesc8Offset) { builder.AddOffset(40, impactDesc8Offset.Value, 0); }
  public static void AddImpactParam8(FlatBufferBuilder builder, int impactParam8) { builder.AddInt(41, impactParam8, 0); }
  public static void AddImpactDesc9(FlatBufferBuilder builder, StringOffset impactDesc9Offset) { builder.AddOffset(42, impactDesc9Offset.Value, 0); }
  public static void AddImpactParam9(FlatBufferBuilder builder, int impactParam9) { builder.AddInt(43, impactParam9, 0); }
  public static void AddImpactDesc10(FlatBufferBuilder builder, StringOffset impactDesc10Offset) { builder.AddOffset(44, impactDesc10Offset.Value, 0); }
  public static void AddImpactParam10(FlatBufferBuilder builder, int impactParam10) { builder.AddInt(45, impactParam10, 0); }
  public static void AddImpactDesc11(FlatBufferBuilder builder, StringOffset impactDesc11Offset) { builder.AddOffset(46, impactDesc11Offset.Value, 0); }
  public static void AddImpactParam12(FlatBufferBuilder builder, int impactParam12) { builder.AddInt(47, impactParam12, 0); }
  public static void AddShow1(FlatBufferBuilder builder, StringOffset Show1Offset) { builder.AddOffset(48, Show1Offset.Value, 0); }
  public static void AddShow2(FlatBufferBuilder builder, StringOffset Show2Offset) { builder.AddOffset(49, Show2Offset.Value, 0); }
  public static Offset<SkillDataTableVO> EndSkillDataTableVO(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SkillDataTableVO>(o);
  }
};


}
