// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Games.TLBB.Table.Static
{

using global::System;
using global::FlatBuffers;
using System.Collections.Generic;

public struct StrDictionaryVO : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static StrDictionaryVO GetRootAsStrDictionaryVO(ByteBuffer _bb) { return GetRootAsStrDictionaryVO(_bb, new StrDictionaryVO()); }
  public static StrDictionaryVO GetRootAsStrDictionaryVO(ByteBuffer _bb, StrDictionaryVO obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public StrDictionaryVO __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Vaule { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetVauleBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<StrDictionaryVO> CreateStrDictionaryVO(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset vauleOffset = default(StringOffset)) {
    builder.StartObject(2);
    StrDictionaryVO.AddVaule(builder, vauleOffset);
    StrDictionaryVO.AddId(builder, Id);
    return StrDictionaryVO.EndStrDictionaryVO(builder);
  }

  public static void StartStrDictionaryVO(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddVaule(FlatBufferBuilder builder, StringOffset vauleOffset) { builder.AddOffset(1, vauleOffset.Value, 0); }
  public static Offset<StrDictionaryVO> EndStrDictionaryVO(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<StrDictionaryVO>(o);
  }
};


}
