// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Game.Table.Static
{

using global::System;
using global::FlatBuffers;
using System.Collections.Generic;

public struct StringDictionaryVO : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static StringDictionaryVO GetRootAsStringDictionaryVO(ByteBuffer _bb) { return GetRootAsStringDictionaryVO(_bb, new StringDictionaryVO()); }
  public static StringDictionaryVO GetRootAsStringDictionaryVO(ByteBuffer _bb, StringDictionaryVO obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public StringDictionaryVO __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string CHValue { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetCHValueBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<StringDictionaryVO> CreateStringDictionaryVO(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset CH_ValueOffset = default(StringOffset)) {
    builder.StartObject(2);
    StringDictionaryVO.AddCHValue(builder, CH_ValueOffset);
    StringDictionaryVO.AddId(builder, Id);
    return StringDictionaryVO.EndStringDictionaryVO(builder);
  }

  public static void StartStringDictionaryVO(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddCHValue(FlatBufferBuilder builder, StringOffset CHValueOffset) { builder.AddOffset(1, CHValueOffset.Value, 0); }
  public static Offset<StringDictionaryVO> EndStringDictionaryVO(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<StringDictionaryVO>(o);
  }
};


}
